version: '3'

services:
  app:
    container_name: lumen
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    tty: true
    networks:
      - lumen
  db:
    container_name: database
    image: mariadb:10.9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "lumen"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    tty: true
    networks:
      - lumen

volumes:
  db_data:
networks:
  lumen: